# Example: Prod RDS \u2013 SSL on, no schema changes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5

# Safer timeouts
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Dev logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=DEBUG
logging.level.com.tps.service=INFO
logging.level.com.tps.controller=INFO
logging.level.com.tps.cache.events=INFO
app.root.tokenId=TRADEPOSTAPP-b49e7a3c1f

security.ip-allowlist=srv1319483.hstgr.cloud,76.13.252.12

